# Uncomment the next line to define a global platform for your project
# use_frameworks!
platform :ios, '11.0'

target 'TrackierSDK' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TrackierSDK
pod 'Alamofire', '~> 5.4.1'
pod 'Willow', '~> 5.0'
pod 'CryptoSwift', '~> 1.4.1'


end
